Repository CSI-CATT-DMCE/kudamcam, pull requests merged in 2022-10, with the labels that each got.

#5 preloader added
  css/style.css
  images/Bounce-Bar-Preloader-1.gif
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#6 Solved Issue for - Center mobile-mockup design for medium and small s…
  css/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#7 quotes added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#13 Join us page added
  css/style.css
  index.html
  joinus.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#11 Update README.md
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#16 adding quotes
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#20 added more quotes
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
